global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'kong'

    static_configs:
      - targets: ['kong:8001']
